/**
 *  @author Yunxiang He
 *  @date Jan 4, 2018 11:02:29 PM
 */

package coding.temp;

/*

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

 */

public class _0389_Find_the_Difference {

    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public char findTheDifference(String s, String t) {
        int res = 0;
        for (char c : (s + t).toCharArray()) {
            res ^= c;
        }
        return (char) res;
    }

    public static void main(String[] args) {
        _0389_Find_the_Difference test = new _0389_Find_the_Difference();
        System.out.println(test.findTheDifference("abcd", "ebacd"));
    }
}
